blank_issues_enabled: false

contact_links:
  - name: GitHub Discussions
    url: https://github.com/ProjectEvergreen/wcc/discussions
    about: Please ask and answer questions here or discuss new ideas for the project.
  - name: Discord
    url: https://www.greenwoodjs.dev/discord/
    about: Chat about Greenwood and join the community!