name: Continuous Integration (Experimental)

on: [pull_request]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [18, 20, 22]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    - name: Installing project dependencies
      run: |
        npm ci
    - name: Lint
      run: |
        npm run lint
    - name: Test
      run: |
        npm run test:exp
    - name: Build
      run: |
        npm run docs:build