name: Master Integration

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node: [16]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - name: Installing project dependencies
      run: |
        npm ci
    - name: Build
      run: |
        npm run build